name: Reusable action that creates an env var
inputs:
  keys:
    description: 'comma delimited key list'
    required: true
on:
  workflow_call:
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        IFS=','
        read -a strarr <<< ${{ inputs.keys }}
        echo "There are ${#strarr[*]} keys in the input"
        for val in "${strarr[@]}";
        do
          echo "$val=$date" >> $GITHUB_ENV
          sleep 1
        done
