name: Reusable action that creates an env var
on:
  workflow_call:
runs:
  using: "composite"
  steps:
    - shell: bash
      run: |
        echo "MESSAGE1=hi" >> $GITHUB_ENV
        echo "MESSAGE2=hi-hi" >> $GITHUB_ENV
   
