name: Reusable action with HTTP Request
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  deploy:
    uses: gmansals/reusable-workflow-sample/.github/workflows/make_http_request.yaml@main
    with:
      branch-name: ${{github.ref}}
