name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  deploy:
    container:
      runs-on: [hfc-runner]
    uses: HFC/security-metrics/.github/workflows/update_deployment_metrics.yaml@main
    with:
      branch-name: ${{github.ref}}
