name: CI
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - develop
jobs:
  deploy:
    uses: gmansals/test-repo/.github/workflows/update_deployment_metrics.yaml@main
    with:
      branch-name: ${{github.ref}}
