name: Shared action with HTTP request
on:
  workflow_call:
    inputs:
      branch-name:
        description: target branch
        required: true
        type: string
jobs:
  nonprod-deploy:
    name: nonprod-deploy
    runs-on: ubuntu-latest
    if: ${{inputs.branch-name}} == "refs/heads/develop"
    steps:
      - name: Echo inputs
        run:
          echo ${{inputs.branch-name}} == "refs/heads/develop"
      - name: Call HTTP GET
        id: callHTTPGet
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://www.google.com/'
          method: 'GET'
          contentType: 'application/json'
          customHeaders: '{"x-api-key":"xyz123"}'
          data: '{}' # request body
      - name: Display HTTP response
        run: echo ${{ steps.callHTTPGet.outputs.response }}
