name: Update deployment metrics
on:
  workflow_call:
    inputs:
      branch-name:
        description: target branch
        required: true
        type: string
jobs:
  nonprod-deploy:
    name: nonprod-deploy
    runs-on: ubuntu-latest
    if: ${{inputs.branch-name}} == 'refs/heads/develop'
    steps:
      - name: Update Deployment Metrics
        id: postNewDeploymentRecord
        uses: fjogeleit/http-request-action@master
        with:
          url: 'https://www.google.com/'
          method: 'GET'
          contentType: 'application/json'
          customHeaders: 'x-api-key: xyz123'
          data: '{}' # request body
      - name: Display HTTP response
        run: echo ${{ steps.postNewDeploymentRecord.outputs.response }}
